name 'sb-mesos'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures sb-mesos'
long_description 'Installs/Configures sb-mesos'
version '0.1.0'

depends 'yum'
depends 'docker'
